name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew.bat shadowJar runtime
      - uses: papeloto/action-zip@v1.1
        with:
          files: build/image build/libs
          dest: TotalDebugCompanion.zip
          recursive: true
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: TotalDebugCompanion.zip
          fail_on_unmatched_files: true
          body: |
            Changes in this Release
            - 1.7.10 release
